server:
  port: 8092

spring:
  application:
    name: orchestration-point
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/point_example
    username: root
    password: hramst0618@

logging:
  level:
    com.example: DEBUG
